language: objective-c
before_script:
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/profile/XC_Ad_Hoc_.mobileprovision.enc -d -a -out scripts/profile/XC_Ad_Hoc_.mobileprovision
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/certs/dist.cer.enc -d -a -out scripts/certs/dist.cer
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/certs/dist.p12.enc -d -a -out scripts/certs/dist.p12
- ./scripts/add-key.sh
- ./scripts/update-bundle.sh
script:
- xctool -project ArrowExample/ArrowExample.xcodeproj -scheme Arrow -sdk iphoneos -configuration Release OBJROOT=$PWD/build SYMROOT=$PWD/build ONLY_ACTIVE_ARCH=NO ONLY_ACTIVE_ARCH=NO CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
after_script:
- ./scripts/remove-key.sh
after_success:
- ./scripts/sign-and-upload.sh


env:
  global:
  - APP_NAME="Arrow"
  - DEVELOPER_NAME="iPhone Distribution: SARL OCTOPEPPER (4TATSTJ3J3)"'
  - PROFILE_NAME="XC_Ad_Hoc_"
  - secure: 5nNz7opxtYNoMbHQswGaQJ2+Me6TjN/Mo9B5WH/NDQox0S6+v8MK7HduiD4LW5G5/h9xg2Dnta8wHDWv/e9T2sh9PRQKZc9EVv+DPA+hPGxEMnNpmm4MJuqm5ct47d96dM8VpO6XHhZsxw+LjPIkEgyc/7J1eoOMKfz4EztZPeiPkkoA7otqQq2kjfXXcrgGz8gWyiyK3FwKQT83C4SFCvHZDji32YTEkb+PAx+l8j0Am3PxXFrp/+fW6btq5sZJY9RjMuqHNoXaUMOUzDTz2Pe4qsYzxTKQvzKslpSNm4NvrxB82uhCmj7VNApgavmhFnJmTVlVIIEpnJaKbLWTgHd/VC8oP5ZxOSP0lmH3zOb2cwiVi6wzilWw3aLobtTFrcJjBggn9nqeCQtAHGyHzjuctlGiWYt4TppXztDsqv4VsfNlWRTh6s7UNjRl/nfkrjDBN4c0RKbfmrkhymGdiA08vBCcz+jnfm0Y2Ua9XIlMOdenXxTgOnKrbB68oPQeOn4h1cwMqFOtv0V2gGQXDCphA8vprxYoDqBRMTDADjW9QcX5gcQwiO3ZhOvKtfKJfQqciLcsyFr3StuBpyHaGRH34YjqBzN7D3qAQi3MmqMNyzpi4/3fMhu39F4ErBzop85J7x2mz9SAI2DVWBfKY3pk54yxJ4gSe6zR35eRIC8=


# xcode_project: ArrowExample/ArrowExample.xcodeproj
# xcode_scheme: Arrow